### ISSUE TITLE
Official v1.0 Scaling Feast TODO list

### ISSUE THREAD

**Issue by yeelp** [yeelp/Scaling-Feast#1]
So here's the scoop. This list contains tasks ideally ordered in priority (but not necessarily ordered by required completion order) for version 1.0 of Scaling Feast. Also I don't know Markdown (rip).

REQUIRED TASKS
---------------------------------------

- [x] Save/load the FoodStatsMap per world. This requires adding a capability to the player and storing it there (probably?).

- [x] Correctly load the texture for the Hearty Shank item. Also fix localization for it.
- [x] Add a crafting recipe for the Hearty Shank item. Dev world contains a preliminary idea.
- [x] Fix localization for Iron Apple

- [x] Add texture for Metabolism and Iron Stomach potion effect
- [x] Overlay the hunger bar in the GUI with alternately coloured shanks to display to the player their ExtendedFoodStats' hunger (Similar to Scaling Health's apporach). 

- [x] Overlay the hunger bar in the GUI again for ExtendedFoodStats' saturation. We also want to draw the player's vanilla saturation to have a nice consistent display of information at all times. This doesn't need to be done if AppleSkin is loaded and doing it for us (check  task 9)
- [x] When the player has the hunger effect, we need to sort of 'blend' the colours from 6.  with the colours of the hunger effect shank (again, similar to Scaling Health. Their system works wonderfully, so I'm going to implement the same kind of system here).

- [x] Compatibility with AppleSkin. This is huge, since this mod uses AppleCore, so AppleSkin is a very likely companion to be running with at any given time. This is easy however (hopefully). If AppleSkin is loaded and AppleSkin is drawing the saturation to the screen, we don't draw the player saturation to the screen, only the ExtendedFoodStats saturation. This may have to be relegated as a config option (Like: "Stop drawing vanilla saturation when appleskin is loaded") as opposed to being checked for dynamically and adjusted accordingly, which may not be possible. It depends on what kind of stuff I can get from appleskin.

- [x] Config file. This would be a nice QOL for end users. When I get around to this, I might submit a new issue for each config option.

- [x] Enchantment mutual exclusion and tweaking. Fasting and Gluttony should be mutually exclusive. Maybe Famine and Eternal Feast as well? Eternal Feast should be a treasure enchant, Gluttony should probably be too. But I haven't decided yet.

- [x] Tweak loots tables for items

- [x] Add brewing recipe for metabolic potion

- [x] Add death penalty

- [x] Add commands.

Optional Task(s)
------------------------
 - [ ] Add the flashing hunger shanks when holding a food item, much like appleskin, to denote how much hunger a food item will heal. May be difficult, since it might wrap around the hunger bar.

- [x] Add Enchanted Iron Apple
- [x] Add and register Metabolic Potion (gives Metabolism)
- [x] Add Tooltips to some items

**Comment by yeelp** [comment]
PR #2 Completes task 1

**Comment by yeelp** [comment]
Commit  141d59ae1e73ad3710801cead00c29e9c69adfbd completes Task 2. New ideas are percolating; may add to this list

**Comment by yeelp** [comment]
Commit 3ef11d7f62cd8dae4508943beae05fe311cdbf07 completes Task 3. Iron Apple was successfully added without any issues EXCEPT for the name. The localization works, but getting the name formatting with the section symbols (for coloured name) isn't quite working. I need to look into this more. Metabolism also needs a texture.

**Comment by yeelp** [comment]
Commit 36a1d2b completes optional task 2 but ALSO completes task 4. Potion effects still need images.

**Comment by yeelp** [comment]
PR #3 does a lot. We get task 5, 6, 7, 8

**Comment by yeelp** [comment]
PR #5 finishes config

**Comment by yeelp** [comment]
All PR's linked. Will add Metabolic Potion, then close issue

**Comment by yeelp** [comment]
We have two more things before this issue can be closed actually. Should be simple

**Comment by yeelp** [comment]
Some commands would be nice. Will add a separate issues if there is a large amount of commands

**Comment by yeelp** [comment]
There's still an optional task left, but it's only an enhancement. Closing now
