### ISSUE TITLE
Official v1.0 Scaling Feast Config File TODO

### ISSUE THREAD

**Issue by yeelp** [yeelp/Scaling-Feast#4]
Okay, this is the config file todo list. Things that I want to be configurable. In no particular order of importance or implementation, this is it (currently). I've divided it up into sections

### Extended Food Stats
- [x] Global Cap
- [x] Increase per Hearty Shank

### Items
- [x] Hearty Shank  Hunger Restored
- [x] Hearty Shank Saturation Modifier

### HUD
- [x] Display Style (Overlay, Numeric)
- [x] Toggle Draw Saturation
- [x] Hunger Display Colours
- [x] Saturation Display Colours

#### AppleSkin 
- [x] Draw exhaustion underlay
- [x] Draw vanilla saturation overlay

**Comment by yeelp** [comment]
2d19880 completes all of the HUD related configs, the ExtendedFoodStats configs, and the compat configs. Most likely anyway
